class ApiArguments():
    ALL_CUSTOMERS = 'all_customers'
    ACTION = 'action'
    USERNAME = 'username'
    USER_NAME = 'user_name'
    USERNAMES = 'usernames'
    CUSTOMER_CONTEXT = 'customer_context'
    CUSTOMERNAME = 'customername'
    CUSTOMER_NAME = 'customer_name'
    CUSTOMER_NAMES = 'customer_names'
    ENABLED = 'enabled'
    GROUP_NAME = 'group_name'
    GROUP_ID = 'group_id'
    GROUP_IDS = 'group_ids'
    PASSWORD = 'password'
    PERMISSIONS = 'permissions'
    NAME = 'name'
    NEW_PASSWORD = 'new_password'
    DOWNLOAD_URL = 'download_url'
    NET_THROTTLE = 'net_throttle'
    CPU_THROTTLE = 'cpu_throttle'
    SERVER_QUEUE_TTL = 'server_queue_ttl'
    AGENT_QUEUE_TTL = 'agent_queue_ttl'
    DELETE_ALL_AGENTS = 'delete_all_agents'
    MOVE_AGENTS_TO_CUSTOMER = 'move_agents_to_customer'
    COUNT = 'count'
    OFFSET = 'offset'
    QUERY = 'query'
    FILTER_KEY = 'filter_key'
    FILTER_VAL = 'filter_val'
    IP = 'ip'
    MAC = 'mac'
    SORT = 'sort'
    SORT_BY = 'sort_by'
    OPERATION = 'operation'
    FULL_NAME = 'full_name'
    EMAIL = 'email'


class ApiValues():
    ADD = 'add'
    DELETE = 'delete'
    TOGGLE = 'toggle'
    YES = 'yes'
    NO = 'no'
