#! /bin/sh

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
NAME=vFense
DESC=vFense
DAEMON="/opt/TopPatch/tp/src/daemon/vFensed"

set -e

case "$1" in
  start)
	sh -c "$DAEMON $1"
        ;;
  stop)
	sh -c "$DAEMON $1"
	;;	
  restart)
	sh -c "$DAEMON $1"
	;;
  status)
	sh -c "$DAEMON $1"
	;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
