[
    {
        "status": "installed", 
        "kb": "", 
        "description": "AppArmor library Perl bindings\n This provides the Perl module that contains the language bindings\n for the AppArmor library, libapparmor, which were autogenerated via\n SWIG.", 
        "support_url": "http://apparmor.net/", 
        "release_date": 0, 
        "vendor_severity": "optional", 
        "install_date": 1417174210, 
        "reboot_required": "no", 
        "uninstallable": "yes", 
        "repo": "", 
        "file_data": [], 
        "dependencies": [], 
        "version": "2.8.95~2430-0ubuntu5.1", 
        "vendor_name": "", 
        "name": "libapparmor-perl"
    }
]