class CommonKeys():
    YES = 'yes'
    NO = 'no'
    COUNT = 'count'
    DETAILS = 'details'
    REDUCTION = 'reduction'
    USERNAME = 'username'
    PASSWORD = 'password'
    USER = 'user'
    URI = 'uri'
    METHOD = 'method'
