import logging, logging.config
from vFense._constants import VFENSE_LOGGING_CONFIG
from vFense.db.client import r
from vFense.db.manager import DbInit
from vFense.plugins.patching._db_model import (
    DbCommonAppIndexes, DbCommonAppKeys, DbCommonAppPerAgentKeys,
    DbCommonAppPerAgentIndexes, AppCollections, FileCollections,
    FilesIndexes, FilesKey
)

logging.config.fileConfig(VFENSE_LOGGING_CONFIG)
logger = logging.getLogger('vfense_api')

collections = [
    (AppCollections.UniqueApplications, DbCommonAppKeys.AppId),
    (AppCollections.CustomApps, DbCommonAppKeys.AppId),
    (AppCollections.SupportedApps, DbCommonAppKeys.AppId),
    (AppCollections.vFenseApps, DbCommonAppKeys.AppId),
    (AppCollections.AppsPerAgent, DbCommonAppPerAgentKeys.Id),
    (AppCollections.CustomAppsPerAgent, DbCommonAppPerAgentKeys.Id),
    (AppCollections.SupportedAppsPerAgent, DbCommonAppPerAgentKeys.Id),
    (AppCollections.vFenseAppsPerAgent, DbCommonAppPerAgentKeys.Id),
    (FileCollections.Files, FilesKey.FileName)
]

secondary_indexes = [
    (
        AppCollections.UniqueApplications,
        DbCommonAppIndexes.vFenseSeverity,
        (
            r
            .table(AppCollections.UniqueApplications)
            .index_create(DbCommonAppIndexes.vFenseSeverity)
        )
    ),
    (
        AppCollections.UniqueApplications,
        DbCommonAppIndexes.Name,
        (
            r
            .table(AppCollections.UniqueApplications)
            .index_create(DbCommonAppIndexes.Name)
        )
    ),
    (
        AppCollections.UniqueApplications,
        DbCommonAppIndexes.NameAndVersion,
        (
            r
            .table(AppCollections.UniqueApplications)
            .index_create(
                DbCommonAppIndexes.NameAndVersion,
                lambda x:
                [
                    x[DbCommonAppKeys.Name],
                    x[DbCommonAppKeys.Version]
                ]
            )
        )
    ),
    (
        AppCollections.UniqueApplications,
        DbCommonAppIndexes.AppIdAndvFenseSeverity,
        (
            r
            .table(AppCollections.UniqueApplications)
            .index_create(
                DbCommonAppIndexes.AppIdAndvFenseSeverity,
                lambda x:
                [
                    x[DbCommonAppKeys.AppId],
                    x[DbCommonAppKeys.vFenseSeverity]
                ]
            )
        )
    ),
    (
        AppCollections.CustomApps,
        DbCommonAppIndexes.vFenseSeverity,
        (
            r
            .table(AppCollections.CustomApps)
            .index_create(DbCommonAppIndexes.vFenseSeverity)
        )
    ),
    (
        AppCollections.CustomApps,
        DbCommonAppIndexes.Name,
        (
            r
            .table(AppCollections.CustomApps)
            .index_create(DbCommonAppIndexes.Name)
        )
    ),
    (
        AppCollections.CustomApps,
        DbCommonAppIndexes.NameAndVersion,
        (
            r
            .table(AppCollections.CustomApps)
            .index_create(
                DbCommonAppIndexes.NameAndVersion,
                lambda x:
                [
                    x[DbCommonAppKeys.Name],
                    x[DbCommonAppKeys.Version]
                ]
            )
        )
    ),
    (
        AppCollections.CustomApps,
        DbCommonAppIndexes.AppIdAndvFenseSeverity,
        (
            r
            .table(AppCollections.CustomApps)
            .index_create(
                DbCommonAppIndexes.AppIdAndvFenseSeverity,
                lambda x:
                [
                    x[DbCommonAppKeys.AppId],
                    x[DbCommonAppKeys.vFenseSeverity]
                ]
            )
        )
    ),
    (
        AppCollections.SupportedApps,
        DbCommonAppIndexes.vFenseSeverity,
        (
            r
            .table(AppCollections.SupportedApps)
            .index_create(DbCommonAppIndexes.vFenseSeverity)
        )
    ),
    (
        AppCollections.SupportedApps,
        DbCommonAppIndexes.Name,
        (
            r
            .table(AppCollections.SupportedApps)
            .index_create(DbCommonAppIndexes.Name)
        )
    ),
    (
        AppCollections.SupportedApps,
        DbCommonAppIndexes.NameAndVersion,
        (
            r
            .table(AppCollections.SupportedApps)
            .index_create(
                DbCommonAppIndexes.NameAndVersion,
                lambda x:
                [
                    x[DbCommonAppKeys.Name],
                    x[DbCommonAppKeys.Version]
                ]
            )
        )
    ),
    (
        AppCollections.SupportedApps,
        DbCommonAppIndexes.AppIdAndvFenseSeverity,
        (
            r
            .table(AppCollections.SupportedApps)
            .index_create(
                DbCommonAppIndexes.AppIdAndvFenseSeverity,
                lambda x:
                [
                    x[DbCommonAppKeys.AppId],
                    x[DbCommonAppKeys.vFenseSeverity]
                ]
            )
        )
    ),
    (
        AppCollections.vFenseApps,
        DbCommonAppIndexes.vFenseSeverity,
        (
            r
            .table(AppCollections.vFenseApps)
            .index_create(DbCommonAppIndexes.vFenseSeverity)
        )
    ),
    (
        AppCollections.vFenseApps,
        DbCommonAppIndexes.Name,
        (
            r
            .table(AppCollections.vFenseApps)
            .index_create(DbCommonAppIndexes.Name)
        )
    ),
    (
        AppCollections.vFenseApps,
        DbCommonAppIndexes.NameAndVersion,
        (
            r
            .table(AppCollections.vFenseApps)
            .index_create(
                DbCommonAppIndexes.NameAndVersion,
                lambda x:
                [
                    x[DbCommonAppKeys.Name],
                    x[DbCommonAppKeys.Version]
                ]
            )
        )
    ),
    (
        AppCollections.vFenseApps,
        DbCommonAppIndexes.AppIdAndvFenseSeverity,
        (
            r
            .table(AppCollections.vFenseApps)
            .index_create(
                DbCommonAppIndexes.AppIdAndvFenseSeverity,
                lambda x:
                [
                    x[DbCommonAppKeys.AppId],
                    x[DbCommonAppKeys.vFenseSeverity]
                ]
            )
        )
    ),
    (
        FileCollections.Files,
        FilesIndexes.FilesDownloadStatus,
        (
            r
            .table(FileCollections.Files)
            .index_create(FilesIndexes.FilesDownloadStatus)
        )
    ),
    (
        AppCollections.AppsPerAgent,
        DbCommonAppPerAgentIndexes.Status,
        (
            r
            .table(AppCollections.AppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.Status
            )
        )
    ),
    (
        AppCollections.AppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentId,
        (
            r
            .table(AppCollections.AppsPerAgent)
            .index_create(DbCommonAppPerAgentIndexes.AgentId)
        )
    ),
    (
        AppCollections.AppsPerAgent,
        DbCommonAppPerAgentIndexes.AppId,
        (
            r
            .table(AppCollections.AppsPerAgent,)
            .index_create(DbCommonAppPerAgentIndexes.AppId)
        )
    ),
    (
        AppCollections.AppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentIdAndAppId,
        (
            r
            .table(AppCollections.AppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AgentIdAndAppId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AgentId],
                    x[DbCommonAppPerAgentKeys.AppId]
                ]
            )
        )
    ),
    (
        AppCollections.AppsPerAgent,
        DbCommonAppPerAgentIndexes.AppIdAndStatus,
        (
            r
            .table(AppCollections.AppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AppIdAndStatus,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AppId],
                    x[DbCommonAppPerAgentKeys.Status]
                ]
            )
        )
    ),
    (
        AppCollections.AppsPerAgent,
        DbCommonAppPerAgentIndexes.StatusAndAgentId,
        (
            r
            .table(AppCollections.AppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.StatusAndAgentId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.Status],
                    x[DbCommonAppPerAgentKeys.AgentId]
                ]
            )
        )
    ),
    (
        AppCollections.CustomAppsPerAgent,
        DbCommonAppPerAgentIndexes.Status,
        (
            r
            .table(AppCollections.CustomAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.Status
            )
        )
    ),
    (
        AppCollections.CustomAppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentId,
        (
            r
            .table(AppCollections.CustomAppsPerAgent)
            .index_create(DbCommonAppPerAgentIndexes.AgentId)
        )
    ),
    (
        AppCollections.CustomAppsPerAgent,
        DbCommonAppPerAgentIndexes.AppId,
        (
            r
            .table(AppCollections.CustomAppsPerAgent,)
            .index_create(DbCommonAppPerAgentIndexes.AppId)
        )
    ),
    (
        AppCollections.CustomAppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentIdAndAppId,
        (
            r
            .table(AppCollections.CustomAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AgentIdAndAppId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AgentId],
                    x[DbCommonAppPerAgentKeys.AppId]
                ]
            )
        )
    ),
    (
        AppCollections.CustomAppsPerAgent,
        DbCommonAppPerAgentIndexes.AppIdAndStatus,
        (
            r
            .table(AppCollections.CustomAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AppIdAndStatus,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AppId],
                    x[DbCommonAppPerAgentKeys.Status]
                ]
            )
        )
    ),
    (
        AppCollections.CustomAppsPerAgent,
        DbCommonAppPerAgentIndexes.StatusAndAgentId,
        (
            r
            .table(AppCollections.CustomAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.StatusAndAgentId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.Status],
                    x[DbCommonAppPerAgentKeys.AgentId]
                ]
            )
        )
    ),
    (
        AppCollections.SupportedAppsPerAgent,
        DbCommonAppPerAgentIndexes.Status,
        (
            r
            .table(AppCollections.SupportedAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.Status
            )
        )
    ),
    (
        AppCollections.SupportedAppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentId,
        (
            r
            .table(AppCollections.SupportedAppsPerAgent)
            .index_create(DbCommonAppPerAgentIndexes.AgentId)
        )
    ),
    (
        AppCollections.SupportedAppsPerAgent,
        DbCommonAppPerAgentIndexes.AppId,
        (
            r
            .table(AppCollections.SupportedAppsPerAgent,)
            .index_create(DbCommonAppPerAgentIndexes.AppId)
        )
    ),
    (
        AppCollections.SupportedAppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentIdAndAppId,
        (
            r
            .table(AppCollections.SupportedAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AgentIdAndAppId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AgentId],
                    x[DbCommonAppPerAgentKeys.AppId]
                ]
            )
        )
    ),
    (
        AppCollections.SupportedAppsPerAgent,
        DbCommonAppPerAgentIndexes.AppIdAndStatus,
        (
            r
            .table(AppCollections.SupportedAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AppIdAndStatus,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AppId],
                    x[DbCommonAppPerAgentKeys.Status]
                ]
            )
        )
    ),
    (
        AppCollections.SupportedAppsPerAgent,
        DbCommonAppPerAgentIndexes.StatusAndAgentId,
        (
            r
            .table(AppCollections.SupportedAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.StatusAndAgentId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.Status],
                    x[DbCommonAppPerAgentKeys.AgentId]
                ]
            )
        )
    ),
    (
        AppCollections.vFenseAppsPerAgent,
        DbCommonAppPerAgentIndexes.Status,
        (
            r
            .table(AppCollections.vFenseAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.Status
            )
        )
    ),
    (
        AppCollections.vFenseAppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentId,
        (
            r
            .table(AppCollections.vFenseAppsPerAgent)
            .index_create(DbCommonAppPerAgentIndexes.AgentId)
        )
    ),
    (
        AppCollections.vFenseAppsPerAgent,
        DbCommonAppPerAgentIndexes.AppId,
        (
            r
            .table(AppCollections.vFenseAppsPerAgent,)
            .index_create(DbCommonAppPerAgentIndexes.AppId)
        )
    ),
    (
        AppCollections.vFenseAppsPerAgent,
        DbCommonAppPerAgentIndexes.AgentIdAndAppId,
        (
            r
            .table(AppCollections.vFenseAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AgentIdAndAppId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AgentId],
                    x[DbCommonAppPerAgentKeys.AppId]
                ]
            )
        )
    ),
    (
        AppCollections.vFenseAppsPerAgent,
        DbCommonAppPerAgentIndexes.AppIdAndStatus,
        (
            r
            .table(AppCollections.vFenseAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.AppIdAndStatus,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.AppId],
                    x[DbCommonAppPerAgentKeys.Status]
                ]
            )
        )
    ),
    (
        AppCollections.vFenseAppsPerAgent,
        DbCommonAppPerAgentIndexes.StatusAndAgentId,
        (
            r
            .table(AppCollections.vFenseAppsPerAgent)
            .index_create(
                DbCommonAppPerAgentIndexes.StatusAndAgentId,
                lambda x:
                [
                    x[DbCommonAppPerAgentKeys.Status],
                    x[DbCommonAppPerAgentKeys.AgentId]
                ]
            )
        )
    )
]

try:
    db = DbInit()
    db.initialize(collections, secondary_indexes)

except Exception as e:
    logger.exception(e)
